In [1]:
import pandas as pd
import numpy as np


In [2]:
a = np.array([[1,2] , [3,4] , [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
b = np.sqrt(a)
b

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [6]:
b.min()

1.0

In [7]:
b.max()

2.449489742783178

In [8]:
b.std()

0.49079386388321616

In [9]:
c = [2,3,4 , 5,6,7,8,9,0]
c[1:6]

[3, 4, 5, 6, 7]

In [10]:
d = np.array([[2,3,4,5,6,7,8,11,12,14]])
d

array([[ 2,  3,  4,  5,  6,  7,  8, 11, 12, 14]])

In [11]:
for row in d:
    for cell in d:
        print(cell)

[ 2  3  4  5  6  7  8 11 12 14]


In [12]:
for x in np.nditer(a , order = "F"):
    print(x)

1
3
5
2
4
6


In [13]:
for x in np.nditer(a , order = "C"):
    print(x)

1
2
3
4
5
6


In [14]:
import pandas as pd

# Make sure to provide the correct file path and name
file_path = r"C:\Users\VAIBHAV KUMAR\OneDrive\Desktop\HR.xlsx"

# Read the Excel file into a DataFrame
df = pd.read_excel(file_path , header = 0)

# Now 'df' contains the data from the Excel file


In [15]:
df

EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230   
1      RM302   18    18-25        No      Travel_Rarely        812   
2      RM458   18    18-25       Yes  Travel_Frequently       1306   
3      RM728   18    18-25        No         Non-Travel        287   
4      RM829   18    18-25       Yes         Non-Travel        247   
...      ...  ...      ...       ...                ...        ...   
1475   RM412   60      55+        No      Travel_Rarely        422   
1476   RM428   60      55+        No  Travel_Frequently       1499   
1477   RM537   60      55+        No      Travel_Rarely       1179   
1478   RM880   60      55+        No      Travel_Rarely        696   
1479  RM1210   60      55+        No      Travel_Rarely        370   

                  Department  DistanceFromHome  Education EducationField  ...  \
0     Research & Development                 3          3  Life Sciences  ...   
1                      Sales                10          3        Medical  ...   
2                      Sales                 5          3      Marketing  ...   
3     Research & Development                 5          2  Life Sciences  ...   
4     Research & Development                 8          1        Medical  ...   
...                      ...               ...        ...            ...  ...   
1475  Research & Development                 7          3  Life Sciences  ...   
1476                   Sales                28          3      Marketing  ...   
1477                   Sales                16          4      Marketing  ...   
1478                   Sales                 7          4      Marketing  ...   
1479  Research & Development                 1          4        Medical  ...   

      RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                            3             80                 0   
1                            1             80                 0   
2                            4             80                 0   
3                            4             80                 0   
4                            4             80                 0   
...                        ...            ...               ...   
1475                         4             80                 0   
1476                         4             80                 0   
1477                         4             80                 0   
1478                         2             80                 1   
1479                         3             80                 1   

     TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
0                    0                      2                3   
1                    0                      2                3   
2                    0                      3                3   
3                    0                      2                3   
4                    0                      0                3   
...                ...                    ...              ...   
1475                33                      5                1   
1476                22                      5                4   
1477                10                      1                3   
1478                12                      3                3   
1479                19                      2                4   

      YearsAtCompany YearsInCurrentRole  YearsSinceLastPromotion  \
0                  0                  0                        0   
1                  0                  0                        0   
2                  0                  0                        0   
3                  0                  0                        0   
4                  0                  0                        0   
...              ...                ...                      ...   
1475              29                  8                       11   
1476              18                 13            

In [16]:
df.fillna(0)

EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230   
1      RM302   18    18-25        No      Travel_Rarely        812   
2      RM458   18    18-25       Yes  Travel_Frequently       1306   
3      RM728   18    18-25        No         Non-Travel        287   
4      RM829   18    18-25       Yes         Non-Travel        247   
...      ...  ...      ...       ...                ...        ...   
1475   RM412   60      55+        No      Travel_Rarely        422   
1476   RM428   60      55+        No  Travel_Frequently       1499   
1477   RM537   60      55+        No      Travel_Rarely       1179   
1478   RM880   60      55+        No      Travel_Rarely        696   
1479  RM1210   60      55+        No      Travel_Rarely        370   

                  Department  DistanceFromHome  Education EducationField  ...  \
0     Research & Development                 3          3  Life Sciences  ...   
1                      Sales                10          3        Medical  ...   
2                      Sales                 5          3      Marketing  ...   
3     Research & Development                 5          2  Life Sciences  ...   
4     Research & Development                 8          1        Medical  ...   
...                      ...               ...        ...            ...  ...   
1475  Research & Development                 7          3  Life Sciences  ...   
1476                   Sales                28          3      Marketing  ...   
1477                   Sales                16          4      Marketing  ...   
1478                   Sales                 7          4      Marketing  ...   
1479  Research & Development                 1          4        Medical  ...   

      RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                            3             80                 0   
1                            1             80                 0   
2                            4             80                 0   
3                            4             80                 0   
4                            4             80                 0   
...                        ...            ...               ...   
1475                         4             80                 0   
1476                         4             80                 0   
1477                         4             80                 0   
1478                         2             80                 1   
1479                         3             80                 1   

     TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
0                    0                      2                3   
1                    0                      2                3   
2                    0                      3                3   
3                    0                      2                3   
4                    0                      0                3   
...                ...                    ...              ...   
1475                33                      5                1   
1476                22                      5                4   
1477                10                      1                3   
1478                12                      3                3   
1479                19                      2                4   

      YearsAtCompany YearsInCurrentRole  YearsSinceLastPromotion  \
0                  0                  0                        0   
1                  0                  0                        0   
2                  0                  0                        0   
3                  0                  0                        0   
4                  0                  0                        0   
...              ...                ...                      ...   
1475              29                  8                       11   
1476              18                 13            

In [17]:
df.replace(-999 , np.nan)

EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230   
1      RM302   18    18-25        No      Travel_Rarely        812   
2      RM458   18    18-25       Yes  Travel_Frequently       1306   
3      RM728   18    18-25        No         Non-Travel        287   
4      RM829   18    18-25       Yes         Non-Travel        247   
...      ...  ...      ...       ...                ...        ...   
1475   RM412   60      55+        No      Travel_Rarely        422   
1476   RM428   60      55+        No  Travel_Frequently       1499   
1477   RM537   60      55+        No      Travel_Rarely       1179   
1478   RM880   60      55+        No      Travel_Rarely        696   
1479  RM1210   60      55+        No      Travel_Rarely        370   

                  Department  DistanceFromHome  Education EducationField  ...  \
0     Research & Development                 3          3  Life Sciences  ...   
1                      Sales                10          3        Medical  ...   
2                      Sales                 5          3      Marketing  ...   
3     Research & Development                 5          2  Life Sciences  ...   
4     Research & Development                 8          1        Medical  ...   
...                      ...               ...        ...            ...  ...   
1475  Research & Development                 7          3  Life Sciences  ...   
1476                   Sales                28          3      Marketing  ...   
1477                   Sales                16          4      Marketing  ...   
1478                   Sales                 7          4      Marketing  ...   
1479  Research & Development                 1          4        Medical  ...   

      RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                            3             80                 0   
1                            1             80                 0   
2                            4             80                 0   
3                            4             80                 0   
4                            4             80                 0   
...                        ...            ...               ...   
1475                         4             80                 0   
1476                         4             80                 0   
1477                         4             80                 0   
1478                         2             80                 1   
1479                         3             80                 1   

     TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
0                    0                      2                3   
1                    0                      2                3   
2                    0                      3                3   
3                    0                      2                3   
4                    0                      0                3   
...                ...                    ...              ...   
1475                33                      5                1   
1476                22                      5                4   
1477                10                      1                3   
1478                12                      3                3   
1479                19                      2                4   

      YearsAtCompany YearsInCurrentRole  YearsSinceLastPromotion  \
0                  0                  0                        0   
1                  0                  0                        0   
2                  0                  0                        0   
3                  0                  0                        0   
4                  0                  0                        0   
...              ...                ...                      ...   
1475              29                  8                       11   
1476              18                 13            

In [18]:
df1 = df.groupby(['Age'])['DailyRate'].sum()
df1 = pd.DataFrame(df1)
df1

DailyRate
Age           
18        5981
19        4936
20        9014
21        9917
22       12911
23        9911
24       22441
25       19970
26       34113
27       43707
28       44520
29       53461
30       47476
31       50362
32       46742
33       42901
34       61326
35       64375
36       57404
37       41386
38       45017
39       33870
40       47978
41       28861
42       32816
43       26184
44       28276
45       34644
46       26474
47       20469
48       15509
49       22300
50       26783
51       18122
52       14340
53       16277
54       13098
55       14217
56       12662
57        1542
58        9667
59        9923
60        4166

In [19]:
df2 = df[['EmpID' , 'Age' , 'AgeGroup']]
df2

EmpID  Age AgeGroup
0      RM297   18    18-25
1      RM302   18    18-25
2      RM458   18    18-25
3      RM728   18    18-25
4      RM829   18    18-25
...      ...  ...      ...
1475   RM412   60      55+
1476   RM428   60      55+
1477   RM537   60      55+
1478   RM880   60      55+
1479  RM1210   60      55+

[1480 rows x 3 columns]

In [20]:
df3 = pd.concat([df1 , df2] , axis = 1)
df3

DailyRate   EmpID  Age AgeGroup
18       5981.0   RM488   20    18-25
19       4936.0   RM514   20    18-25
20       9014.0   RM663   20    18-25
21       9917.0   RM690   20    18-25
22      12911.0   RM732   20    18-25
...         ...     ...  ...      ...
1475        NaN   RM412   60      55+
1476        NaN   RM428   60      55+
1477        NaN   RM537   60      55+
1478        NaN   RM880   60      55+
1479        NaN  RM1210   60      55+

[1480 rows x 4 columns]

In [21]:
merged_df = pd.merge(df3, df2, on='EmpID')
merged_df

DailyRate   EmpID  Age_x AgeGroup_x  Age_y AgeGroup_y
0        5981.0   RM488     20      18-25     20      18-25
1        4936.0   RM514     20      18-25     20      18-25
2        9014.0   RM663     20      18-25     20      18-25
3        9917.0   RM690     20      18-25     20      18-25
4       12911.0   RM732     20      18-25     20      18-25
...         ...     ...    ...        ...    ...        ...
1495        NaN   RM412     60        55+     60        55+
1496        NaN   RM428     60        55+     60        55+
1497        NaN   RM537     60        55+     60        55+
1498        NaN   RM880     60        55+     60        55+
1499        NaN  RM1210     60        55+     60        55+

[1500 rows x 6 columns]

In [22]:
import pandas as pd

data = {
    'Date': ['2022-01-01', '2022-01-01', '2022-01-02', '2022-01-02'],
    'Category': ['A', 'B', 'A', 'B'],
    'Value': [10, 20, 30, 40]
}

dff = pd.DataFrame(data)


In [23]:
pivot_df = dff.pivot(index='Date', columns='Category', values='Value')
pivot_df

Category     A   B
Date              
2022-01-01  10  20
2022-01-02  30  40

In [29]:
import pandas as pd

# Create a sample DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}, index=['row1', 'row2', 'row3'])

# Select a single element
value = df.loc['row1', 'A']

# Select a row
row_data = df.loc['row2']

# Select a column
column_data = df.loc[:, 'B']

# Select a subset of rows and columns
subset = df.loc[['row1', 'row3'], ['A', 'B']]


In [33]:
df

A  B  C
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [32]:
row_data

A    2
B    5
C    8
Name: row2, dtype: int64

In [31]:
# Select a single element
value = df.iloc[0, 0]

# Select a row
row_data = df.iloc[1]

# Select a column
column_data = df.iloc[:, 1]

# Select a subset of rows and columns
subset = df.iloc[0:2, 0:2]


In [36]:
tup = (1,2,3,4,5)
tup[0]


1

In [37]:
tup[2]

3

In [38]:
tup.count(2)

1

In [40]:
tup.index(2)

1